project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Credit Risk"
  author: "Guillaume Gilles"
  date: "5/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: assets/references.bib

format:
  html:
    theme: cosmo
